package trackport

import (
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
	"github.com/sirupsen/logrus"
	"github.com/vishvananda/netns"
	"net"
	"syscall"
)

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -type event bpf fentry.c -- -I./headers

type PortTracker struct {
	tcp bool
	udp bool

	event chan *PortEvent
}

type (
	Protocol = uint16
	Action   = uint16
)

const (
	TCP Protocol = iota
	UDP
)

const (
	OPEN Action = iota
	CLOSE
)

type PortEvent struct {
	Protocol Protocol
	Action   Action
	Ip       net.IP
	Port     string
}

func NewTracker(event chan *PortEvent, udp bool) *PortTracker {
	return &PortTracker{event: event, tcp: true, udp: udp}
}

func (m *PortTracker) Run(ctx context.Context) error {
	// Allow the current process to lock memory for eBPF resources.
	if err := rlimit.RemoveMemlock(); err != nil {
		return err
	}

	objs := bpfObjects{}
	if err := loadBpfObjects(&objs, nil); err != nil {
		return err
	}
	defer objs.Close()

	tcpPgms := []*ebpf.Program{
		objs.bpfPrograms.InetCskAccept,
		objs.bpfPrograms.InetCskListenStop,
	}
	udpPgms := []*ebpf.Program{
		objs.bpfPrograms.InetBindSk,
		objs.bpfPrograms.Inet6BindSk,
		objs.bpfPrograms.UdpDestroySock,
		objs.bpfPrograms.Udpv6DestroySock,
	}

	links := make([]link.Link, 10)
	if m.tcp {
		for _, pgm := range tcpPgms {
			traceLink, err := link.AttachTracing(link.TracingOptions{
				Program: pgm,
			})
			if err != nil {
				return err
			}
			links = append(links, traceLink)
		}
	}

	if m.udp {
		for _, pgm := range udpPgms {
			traceLink, err := link.AttachTracing(link.TracingOptions{
				Program: pgm,
			})
			if err != nil {
				return err
			}
			links = append(links, traceLink)
		}
	}

	defer func() {
		for _, traceLink := range links {
			traceLink.Close()
		}
	}()

	pidNs := make(map[int]string)
	ns, _ := netns.Get()
	uniqueId := ns.UniqueId()

	rd, err := ringbuf.NewReader(objs.bpfMaps.Events)
	if err != nil {
		return err
	}
	defer rd.Close()

	// bpfEvent is generated by bpf2go.
	var event bpfEvent
	for {
		if ctx.Err() != nil {
			return nil
		}
		record, err := rd.Read()
		if err != nil {
			if errors.Is(err, ringbuf.ErrClosed) {
				logrus.Errorf("received signal, exiting..")
				return nil
			}
			logrus.Errorf("reading from reader: %s", err)
			continue
		}

		// Parse the ringbuf event entry into a bpfEvent structure.
		if err := binary.Read(bytes.NewBuffer(record.RawSample), binary.BigEndian, &event); err != nil {
			logrus.Errorf("parsing ringbuf event: %s", err)
			continue
		}

		eventNs, err := netns.GetFromPid(int(event.Pid))
		eventId := eventNs.UniqueId()
		if eventNs == -1 {
			eventId = pidNs[int(event.Pid)]
		}
		if uniqueId == eventId {
			pidNs[int(event.Pid)] = eventId
			ip := intToIP(event.Family, event.Saddr)
			port := fmt.Sprintf("%d", event.Sport)
			m.event <- &PortEvent{Action: event.Action, Protocol: event.Proto, Ip: ip, Port: port}
			if event.Action != CLOSE {
				continue
			}
		}
		delete(pidNs, int(event.Pid))
	}
}

// intToIP converts IPv4 number to net.IP
func intToIP(family uint32, ipNum uint32) net.IP {
	var ip net.IP
	afInet6 := uint32(syscall.AF_INET6)
	afInet6BigEndian := afInet6 << 24

	if family == afInet6BigEndian {
		ip = make(net.IP, 16)
	} else {
		ip = make(net.IP, 4)
	}

	binary.BigEndian.PutUint32(ip, ipNum)
	return ip
}
