package bpftracker

import (
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"github.com/balajiv113/trackport/pkg/trackapi"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
	"github.com/sirupsen/logrus"
	"net"
	"strconv"
	"syscall"
)

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -target arm64,amd64,arm,riscv64 --no-global-types -type event bpf bpf/tracer.c -- -I./bpf/headers
type EbpfPortTracker struct {
	CallbackFn func(event *trackapi.PortEvent)
}

func NewTracker(callbackFn func(event *trackapi.PortEvent)) (trackapi.PortTracker, error) {
	return &EbpfPortTracker{CallbackFn: callbackFn}, nil
}

func (m *EbpfPortTracker) Run(ctx context.Context) error {
	// Allow the current process to lock memory for eBPF resources.
	if err := rlimit.RemoveMemlock(); err != nil {
		return err
	}

	objs := bpfObjects{}
	if err := loadBpfObjects(&objs, nil); err != nil {
		return err
	}
	defer func(objs *bpfObjects) {
		err := objs.Close()
		if err != nil {
			logrus.Error("error during close of bpfObjects", err)
		}
	}(&objs)

	probes := LoadProbes(objs)
	links := make(map[string]link.Link)
	for funcName, probe := range probes {
		probeLink, err := RunProbe(funcName, probe)
		if err != nil {
			return err
		}
		links[funcName] = probeLink
	}

	defer func() {
		for _, probeLink := range links {
			err := probeLink.Close()
			if err != nil {
				logrus.Error("error during close of link", err)
			}
		}
	}()

	rd, err := ringbuf.NewReader(objs.bpfMaps.Events)
	if err != nil {
		return err
	}
	defer func(rd *ringbuf.Reader) {
		err := rd.Close()
		if err != nil {
			logrus.Error("Ringbuffer error during close", err)
		}
	}(rd)

	bindings := make(map[uint32]string)
	ns, _ := getCurrentNetNS()

	// bpfEvent is generated by bpf2go.
	var event bpfEvent
	for {
		if ctx.Err() != nil {
			return nil
		}
		record, err := rd.Read()
		if err != nil {
			if errors.Is(err, ringbuf.ErrClosed) {
				logrus.Errorf("received signal, exiting..")
				return nil
			}
			logrus.Errorf("reading from reader: %s", err)
			continue
		}

		// Parse the ringbuf event entry into a bpfEvent structure.
		if err := binary.Read(bytes.NewBuffer(record.RawSample), binary.LittleEndian, &event); err != nil {
			logrus.Errorf("parsing ringbuf event: %s", err)
			continue
		}
		if ns == event.Netns {
			if event.Action == trackapi.OPEN {
				bindings[event.Pid] = ""
				m.CallbackFn(&trackapi.PortEvent{
					Protocol: event.Proto,
					Action:   event.Action,
					Ip:       ReconstructIPAddress(event),
					Port:     strconv.Itoa(int(event.Port)),
				})
			} else if _, ok := bindings[event.Pid]; ok {
				m.CallbackFn(&trackapi.PortEvent{
					Protocol: event.Proto,
					Action:   event.Action,
					Ip:       ReconstructIPAddress(event),
					Port:     strconv.Itoa(int(event.Port)),
				})
				delete(bindings, event.Pid)
			}
		}
	}
}

func getCurrentNetNS() (uint32, error) {
	var stat syscall.Stat_t
	err := syscall.Stat("/proc/self/ns/net", &stat)
	if err != nil {
		return 0, err
	}
	return uint32(stat.Ino), nil
}

func ReconstructIPAddress(event bpfEvent) net.IP {
	if event.Version == 0 {
		ip := make([]byte, net.IPv4len)
		binary.BigEndian.PutUint32(ip[0:4], uint32(event.IpL))
		return ip
	} else {
		ip := make([]byte, net.IPv6len)
		binary.BigEndian.PutUint64(ip[0:8], event.IpH)
		binary.BigEndian.PutUint64(ip[8:16], event.IpL)
		return ip
	}
}
