// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package bpftracker

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfEvent struct {
	IpL     uint64
	IpH     uint64
	Port    uint16
	_       [2]byte
	Netns   uint32
	Pid     uint32
	Proto   uint16
	Version uint16
	Action  uint16
	_       [6]byte
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	FentryInet6Bind         *ebpf.ProgramSpec `ebpf:"fentry__inet6_bind"`
	FentryInetBind          *ebpf.ProgramSpec `ebpf:"fentry__inet_bind"`
	FentryInetCskAccept     *ebpf.ProgramSpec `ebpf:"fentry__inet_csk_accept"`
	FentryInetCskListenStop *ebpf.ProgramSpec `ebpf:"fentry__inet_csk_listen_stop"`
	FentryUdpDestroySock    *ebpf.ProgramSpec `ebpf:"fentry__udp_destroy_sock"`
	FentryUdpv6DestroySock  *ebpf.ProgramSpec `ebpf:"fentry__udpv6_destroy_sock"`
	FexitInet6Bind          *ebpf.ProgramSpec `ebpf:"fexit__inet6_bind"`
	FexitInetBind           *ebpf.ProgramSpec `ebpf:"fexit__inet_bind"`
	KprobeInetBind          *ebpf.ProgramSpec `ebpf:"kprobe__inet_bind"`
	KprobeInetCskAccept     *ebpf.ProgramSpec `ebpf:"kprobe__inet_csk_accept"`
	KprobeInetCskListenStop *ebpf.ProgramSpec `ebpf:"kprobe__inet_csk_listen_stop"`
	KprobeUdpDestroySock    *ebpf.ProgramSpec `ebpf:"kprobe__udp_destroy_sock"`
	KretprobeInetBind       *ebpf.ProgramSpec `ebpf:"kretprobe__inet_bind"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Events     *ebpf.MapSpec `ebpf:"events"`
	UdpPending *ebpf.MapSpec `ebpf:"udp_pending"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
	Unused *ebpf.VariableSpec `ebpf:"unused"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Events     *ebpf.Map `ebpf:"events"`
	UdpPending *ebpf.Map `ebpf:"udp_pending"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Events,
		m.UdpPending,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
	Unused *ebpf.Variable `ebpf:"unused"`
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	FentryInet6Bind         *ebpf.Program `ebpf:"fentry__inet6_bind"`
	FentryInetBind          *ebpf.Program `ebpf:"fentry__inet_bind"`
	FentryInetCskAccept     *ebpf.Program `ebpf:"fentry__inet_csk_accept"`
	FentryInetCskListenStop *ebpf.Program `ebpf:"fentry__inet_csk_listen_stop"`
	FentryUdpDestroySock    *ebpf.Program `ebpf:"fentry__udp_destroy_sock"`
	FentryUdpv6DestroySock  *ebpf.Program `ebpf:"fentry__udpv6_destroy_sock"`
	FexitInet6Bind          *ebpf.Program `ebpf:"fexit__inet6_bind"`
	FexitInetBind           *ebpf.Program `ebpf:"fexit__inet_bind"`
	KprobeInetBind          *ebpf.Program `ebpf:"kprobe__inet_bind"`
	KprobeInetCskAccept     *ebpf.Program `ebpf:"kprobe__inet_csk_accept"`
	KprobeInetCskListenStop *ebpf.Program `ebpf:"kprobe__inet_csk_listen_stop"`
	KprobeUdpDestroySock    *ebpf.Program `ebpf:"kprobe__udp_destroy_sock"`
	KretprobeInetBind       *ebpf.Program `ebpf:"kretprobe__inet_bind"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.FentryInet6Bind,
		p.FentryInetBind,
		p.FentryInetCskAccept,
		p.FentryInetCskListenStop,
		p.FentryUdpDestroySock,
		p.FentryUdpv6DestroySock,
		p.FexitInet6Bind,
		p.FexitInetBind,
		p.KprobeInetBind,
		p.KprobeInetCskAccept,
		p.KprobeInetCskListenStop,
		p.KprobeUdpDestroySock,
		p.KretprobeInetBind,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_arm64_bpfel.o
var _BpfBytes []byte
